ruyi-repo = "v1"

[repo]
doc_uri = "https://github.com/xen0n/ruyi-addons-loongson"
id = "test-loongson"
name = "TESTING-ONLY add-on ruyi repository for Loongson/LoongArch support"

# Mirrors of third-party software

[[mirrors]]
id = "loongson-build-tools"
urls = [
  "https://github.com/loongson/build-tools/releases/download/",
]
